# adopted from https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI
language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-25 #system image for emulator used
                                     #to run UI Tests

      # Unhash the below line for Google Play Service
      # -extra-google-m2repository
script:
  - ./gradlew build

jdk:
  - oraclejdk8  # lamba expression support
